from enum import Enum

class State(Enum):
    SEARCHING = 1
    SEARCH_TRANSLATING = 2
    SEARCH_TRANSLATING_DONE = 3
    SEARCH_ROTATING1 = 3
    SEARCH_ROTATING1_DONE = 4
    SEARCH_ROTATING2 = 5
    SEARCH_ROTATING2_DONE = 6
    ANIMAL_NAVIGATING = 7
    COMPLETE = 8