
autonomy_finals:
  ros__parameters:

    task_nums: [1, 2, 3, 4, 6, 8]
    docking_num: 3
    ball_shooter_num: 6
    water_shooter_num: 7
    
    docking_secs: 5
    water_secs: 5

    t1_auto: True
    t2_auto: False
    t3_auto: True
    t4_auto: True
    t5_auto: False
    t6_auto: True
    t7_auto: False
    t8_auto: False

    t1_extra_forward_nav: 3.0
    t1_final_extra_forward_nav: 2.0
    t1_gate_buoy_max_dist: 25.0

    t2_trans_x: 8.0
    t2_trans_y: 3.0

    timeouts:
      t1_find_next_gate: 5
    
    timeout_responses:
      t1_find_next_gate_trans: 10.0
