microstrain_inertial_driver:
  ros__parameters:
    # Copy this file to a new file, fill out this section with desired parameters, and specify the new file via params_file to override the default params
    device_setup: True
    debug: True
    diagnostics: True
    publish_filter: True
    filter_auto_init: True
    filter_sensor2vehicle_frame_selector: 0
