
camera_config:
  bow_camera_topics: [
      "/wamv/sensors/cameras/front_left_camera",
      "/wamv/sensors/camera/front_right_camera"
    ]
  bow_camera_frames: [
    "wamv/front_left_camera_link_optical",
    "wamv/front_right_camera_link_optical"
  ]