controller_basic_PID:
  ros__parameters:
    basic_kp: 0.25
    basic_kd: 0.5
    basic_ki: 1.0
    basic_rotate_kp: 1.0
    basic_rotate_kd: 1.0
    basic_rotate_ki: 1.0

controller_velocity_PID:
  ros__parameters:
    #Gain on magnitude of target velocity (to combat drag)
    velocity_k_drag: 1.0
    #Gain on magnitude of velocity error
    velocity_k_error: 1.0
    #gain on integral of error
    velocity_ki: 1.0
