from enum import Enum

class State(Enum):
    START = 1
    STATION_KEEPING_ENABLED = 2
    FINDING_NEXT_GATE = 3
    ROTATING_TO_FIND_NEXT_GATE = 4
    NAVIGATING = 5
    EXTRA_FORWARD_NAV = 6
    COMPLETE = 7