
autonomy_loop:
  ros__parameters:
    gate_use_lidar: True
    gate_use_camera: False
    gate_max_buoy_dist: 25.0 
    gate_extra_forward_nav: 15.0

    loop_use_lidar: True
    loop_use_camera: False
    loop_max_buoy_dist: 25.0

    looping_radius: 4.0
