from enum import Enum

class State(Enum):
    START = 1
    T1_FINDING_NEXT_GATE = 2
    T1_NAVIGATING = 3 
    T1_EXTRA_FORWARD_NAV = 4
    T1_FINAL_EXTRA_FORWARD_NAV = 5
    T2_ENTERING = 6
    T2_BACKING = 7
    T3_LOOP_EXPLORE_INITIAL_NAVIGATION = 8
    T3_LOOP_EXPLORE_ROTATING = 9
    T3_LOOP_EXPLORE_FINDING = 10
    T3_LOOP_EXPLORE_EXTRA_NAVIGATION = 11
    T3_LOOP_APPROACH = 12
    T3_GATE_EXPLORE_NAVIGATION = 13
    T3_GATE_EXPLORE_FINDING = 14
    T3_GATE_EXPLORE_EXTRA_NAVIGATION = 15
    T3_GATE_ENTER = 16
    T3_GATE_EXTRA_FORWARD_NAV = 17
    T3_GATE_REENTER = 18
    T3_BUOY_LOOPING = 19
    T3_EXIT_EXTRA_FORWARD_NAV = 20

