from enum import Enum

class State(Enum):
    START = 1
    STATION_KEEPING_ENABLED = 2
    APPROACHING_DOCK = 3
    FINDING_ORIENTATION = 4
    ORIENTING = 5
    SEARCHING_FOR_DOCK_CODE = 6
    SEARCH_TRANSLATING = 7
    CENTERING = 8
    CENTER_TRANSLATING = 9
    DOCKING = 10
    COUNTING_CODE = 11
    COMPLETE = 12