from enum import Enum

class State(Enum):
    START = 1
    STATION_KEEPING_ENABLED = 2
    FINDING_DOCKS = 3
    APPROACHING = 4
    APPROACHING_COMPLETE = 5
    TRANSLATING = 6
    COMPLETED_TRANSLATION = 7
    ENTERING_DOCK = 8
    AT_ENTERANCE = 9
    ENTERING_FURTHER = 10
    COMPLETE = 11