from enum import Enum

class State(Enum):
    START = 1
    STATION_KEEPING_ENABLED = 2
    APPROACHING = 3
    APPROACHING_COMPLETE = 4
    TRANSLATING = 5
    COMPLETED_TRANSLATION = 6
    ENTERING_DOCK = 7
    AT_ENTERANCE = 8
    ENTERING_FURTHER = 9
    COMPLETE = 10