
lidar_config:

  all_lidar_types: [ # in our case, either hokuyo or vlp16
    'vlp16'
  ]
  all_lidar_base_topics: [
    '/lidars/front_lidar'
  ]
  all_lidar_transforms: [ # from base_link
    [1.0, 0.0, 0.0]
  ]
  all_lidar_frames: [
    'front_lidar_link'
  ]
