
processing_self_filter:
  ros__parameters:
    radius: 0.9

processing_shore_filter:
  ros__parameters:
    x_min: 0.0
    y_min: -10.0
    y_max: 10.0

processing_voxels:
  ros__parameters:
    leaf_size:
      x: 0.01
      y: 0.01
      z: 0.01