
lidar_config:

  all_lidar_types: [ # in our case, either hokuyo or vlp16
    'hokuyo'
  ]
  all_lidar_base_topics: [
    'wamv/sensors/lidars/lidar_wamv'
  ]
  all_lidar_frames: [
    'wamv/lidar_wamv_link'
  ]